upstream orvya_api {
    server api:8000;
}

server {
    listen 80;
    server_name app.orvya.net localhost;

    location /api/ {
        proxy_pass http://orvya_api;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /usr/share/nginx/html/app;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name admin.orvya.net;

    location /api/ {
        proxy_pass http://orvya_api;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /usr/share/nginx/html/admin;
        try_files $uri $uri/ /index.html;
    }
}
